// Emits the Meontor wordmark as SVG outlines: SF Pro Rounded Semibold 48pt,
// tracking -0.6, exactly as MeontorWordmark draws it in the app.
// Usage: swift scripts/export-wordmark.swift > src/lib/assets/wordmark-path.ts
import AppKit
import CoreText

let base = NSFont.systemFont(ofSize: 48, weight: .semibold)
let font = NSFont(descriptor: base.fontDescriptor.withDesign(.rounded)!, size: 48)!
let text = NSAttributedString(string: "Meontor", attributes: [.font: font, .kern: -0.6])
let line = CTLineCreateWithAttributedString(text)
let bounds = CTLineGetBoundsWithOptions(line, .useGlyphPathBounds)

var d = ""
func add(_ path: CGPath, _ t: CGAffineTransform) {
	path.applyWithBlock { el in
		let p = el.pointee.points
		func pt(_ i: Int) -> String {
			let q = p[i].applying(t)
			return String(format: "%.2f %.2f", q.x - bounds.minX, bounds.maxY - q.y)
		}
		switch el.pointee.type {
		case .moveToPoint: d += "M\(pt(0))"
		case .addLineToPoint: d += "L\(pt(0))"
		case .addQuadCurveToPoint: d += "Q\(pt(0)) \(pt(1))"
		case .addCurveToPoint: d += "C\(pt(0)) \(pt(1)) \(pt(2))"
		case .closeSubpath: d += "Z"
		@unknown default: break
		}
	}
}
for run in CTLineGetGlyphRuns(line) as! [CTRun] {
	let runFont = (CTRunGetAttributes(run) as NSDictionary)[kCTFontAttributeName] as! CTFont
	let n = CTRunGetGlyphCount(run)
	var glyphs = [CGGlyph](repeating: 0, count: n)
	var positions = [CGPoint](repeating: .zero, count: n)
	CTRunGetGlyphs(run, CFRange(), &glyphs)
	CTRunGetPositions(run, CFRange(), &positions)
	for i in 0..<n {
		if let path = CTFontCreatePathForGlyph(runFont, glyphs[i], nil) {
			add(path, CGAffineTransform(translationX: positions[i].x, y: positions[i].y))
		}
	}
}
print("// Generated by scripts/export-wordmark.swift. Do not edit.")
print(String(format: "export const WORDMARK_VIEWBOX = '0 0 %.2f %.2f';", bounds.width, bounds.height))
print("export const WORDMARK_PATH = '\(d)';")
